image: openjdk:8u292-jre-buster


before_script:
  - java -version
  - apt-get update && apt-get --assume-yes install wget make procps software-properties-common
  #- apt-get --assume-yes install python3 python3-pip
  #- pip3 install biopython==1.76
  - wget -qO- https://get.nextflow.io | bash && cp nextflow /usr/local/bin/nextflow
  - nextflow help
  - wget -q https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-Linux-x86_64.sh
  - mkdir /root/.conda
  - bash Mambaforge-Linux-x86_64.sh -b -p /usr/local/bin/conda
  - rm -f Mambaforge-Linux-x86_64.sh
  - source /usr/local/bin/conda/etc/profile.d/conda.sh
  - source /usr/local/bin/conda/etc/profile.d/mamba.sh
  - which mamba 
  - mamba --version
  # this is a workaround for https://github.com/mamba-org/mamba/issues/1993
  - echo "use_lockfiles:" >> ~/.condarc
  - echo "  - false" >> ~/.condarc
  - echo "channels:" >> ~/.condarc
  - echo "  - defaults" >> ~/.condarc
  - echo "  - conda-forge" >> ~/.condarc
  - echo "  - bioconda" >> ~/.condarc
  - cat ~/.condarc


stages:
  - test

test:
  stage: test
  script:
    - make
