# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: covigator-pipeline
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::python=3.8.5
  - conda-forge::biopython=1.79
  - bioconda::nextflow=21.04.0
  - bioconda::bcftools=1.12
  - bioconda::lofreq=2.1.5
  - bioconda::gatk4=4.2.0.0
  - bioconda::ivar=1.3.1
  - bioconda::fastp=0.20.1
  - bioconda::snpeff=5.0